version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: messenger_db
    ports:
      - "5444:5432"   # фиксированный порт для pet-проекта
    volumes:
      - messenger_pet_pg_data:/var/lib/postgresql/data

volumes:
  messenger_pet_pg_data: